### ISSUE TITLE
sir need help week 6 quiz

### ISSUE THREAD

**Issue by pjajagtap** [AndriiLiapko/UCSD_MOOC_UnfoldingMaps#1]
1. What is the magnitude of the 6th earthquake printed (i.e. the 6th strongest earthquake)? To be clear, if there are two earthquakes of the same magnitude, each magnitude will count. For example, if the top 4 magnitudes are {7, 6.9, 6.9, and 6}, the 4th largest is 6.
.....................................................................................................................................................
2. Call sortAndPrint as appropriate to answer the following question.

What is the strongest magnitude that is repeated three or more times in the data set?

pls sir help

**Comment by AndriiLiapko** [comment]
For me, first 10 quakes are : 

------Printing Quakes------------
#1 Magnitude: 7.0
Is a land quake.
Country: Indonesia
------------------------------------
#2 Magnitude: 7.0
Is an ocean quake
Depth: 10.0
------------------------------------
#3 Magnitude: 6.9
Is an ocean quake
Depth: 27.0
------------------------------------
#4 Magnitude: 6.6
Is an ocean quake
Depth: 15.0
------------------------------------
#5 Magnitude: 6.5
Is an ocean quake
Depth: 10.0
------------------------------------
#6 Magnitude: 6.4
Is an ocean quake
Depth: 5.0
------------------------------------
#7 Magnitude: 6.3
Is a land quake.
Country: United States of America
------------------------------------
#8 Magnitude: 6.0
Is an ocean quake
Depth: 59.2
------------------------------------
#9 Magnitude: 5.9
Is a land quake.
Country: Afghanistan
------------------------------------
#10 Magnitude: 5.9
Is an ocean quake
Depth: 10.0
