### ISSUE TITLE
Sir I want quiz answers of week 6 of this below question

### ISSUE THREAD

**Issue by pjajagtap** [AndriiLiapko/UCSD_MOOC_UnfoldingMaps#2]
What is the magnitude of the 6th earthquake printed (i.e. the 6th strongest earthquake)? To be clear, if there are two earthquakes of the same magnitude, each magnitude will count. For example, if the top 4 magnitudes are {7, 6.9, 6.9, and 6}, the 4th largest is 6.
.....................................................................................................................................................
Call sortAndPrint as appropriate to answer the following question.
What is the strongest magnitude that is repeated three or more times in the data set?

pls sir help

**Comment by AndriiLiapko** [comment]
answer -- > 5.9
Men, for me it's ok to help, but if your final goal is to get a dev job than you will probably want to put some effort into solving problems on your own and not just asking what is the answer for the quiz questions.
